Adding dynamically layers:
https://discuss.pytorch.org/t/dynamically-add-or-delete-layers/10447/5


In [31]:
'''
This is zip, *zip for transposing a matrix...
'''
orig = [('a', 1), ('b', 2), ('c', 3), ('d', 4)]
print("orig:")
print(orig)
vec = zip(*orig)
print("transposed:")
print(list(vec))

orig:
[('a', 1), ('b', 2), ('c', 3), ('d', 4)]
transposed:
[('a', 'b', 'c', 'd'), (1, 2, 3, 4)]


In [32]:
'''
This is a working example of embedding layer. 
'''
import torch
import torch.nn as nn
from torch.autograd import Variable
import numpy as np
N, D_in, H, D_out = 3, 2, 2, 1

x = Variable(torch.LongTensor([2,0,1]))

# Embedding layer
# Taken from https://discuss.pytorch.org/t/can-we-use-pre-trained-word-embeddings-for-weight-initialization-in-nn-embedding/1222
embed = nn.Embedding(N, D_in)
base = np.array([[0,1],[1,0],[0.5,0.5]])
embed.weight.data.copy_(torch.from_numpy(base))
# make it constant 
embed.weight.requires_grad = False

model = torch.nn.Sequential(
    embed,
)
print("The model:")
print(model)

# Continue, make the parameters constant
# parameters = filter(lambda p: p.requires_grad, model.parameters())
y_pred = model(x)
print(y_pred)


The model:
Sequential(
  (0): Embedding(3, 2)
)
Variable containing:
 0.5000  0.5000
 0.0000  1.0000
 1.0000  0.0000
[torch.FloatTensor of size 3x2]



In [14]:
x

Variable containing:
 0
 1
 2
[torch.IntTensor of size 3]

In [34]:
import numpy as np
base = np.identity(3)
idx = range(2)
base[idx]

array([[1., 0., 0.],
       [0., 1., 0.]])

In [39]:

# Can we approximate some function with NN?
import numpy as np
x = np.linspace(0,10,1000)
y = np.sin(x)

In [40]:
print(y)

[ 0.          0.01000984  0.02001868  0.03002552  0.04002934  0.05002916
  0.06002396  0.07001275  0.07999452  0.08996827  0.09993302  0.10988774
  0.11983146  0.12976317  0.13968188  0.14958659  0.15947632  0.16935006
  0.17920684  0.18904566  0.19886554  0.20866549  0.21844453  0.22820168
  0.23793597  0.24764642  0.25733206  0.26699191  0.276625    0.28623038
  0.29580708  0.30535414  0.3148706   0.32435552  0.33380793  0.3432269
  0.35261147  0.36196071  0.37127369  0.38054946  0.3897871   0.39898569
  0.4081443   0.41726201  0.42633791  0.4353711   0.44436066  0.45330569
  0.46220531  0.47105861  0.47986471  0.48862273  0.49733179  0.50599102
  0.51459954  0.52315651  0.53166105  0.54011232  0.54850948  0.55685167
  0.56513807  0.57336784  0.58154016  0.58965421  0.59770917  0.60570425
  0.61363863  0.62151153  0.62932216  0.63706972  0.64475345  0.65237258
  0.65992634  0.66741398  0.67483474  0.68218788  0.68947267  0.69668838
  0.70383427  0.71090964  0.71791378  0.72484599  0.

In [5]:
import numpy as np

def get_random_sparse_vector(X, B, random_state):
    # initialize the size
    P_vec = np.zeros(shape=(X,))
    # put in the first places 0:B all the random variables.
    P_vec[0:B] = random_state.uniform(low=0, high=1.0, size=(B,))

    # initialize the size
    R_vec = np.zeros(shape=(X,))
    # put in the first places 0:B all the random variables.
    R_vec[0:B] = random_state.normal(size=(B,))


    P_vec[0:B] = P_vec[0:B] / np.sum(P_vec[0:B])
    idx = random_state.permutation([x for x in range(X)])
    P_vec = P_vec[idx]
    R_vec = R_vec[idx]
    return P_vec, R_vec

get_random_sparse_vector(10,4,np.random.RandomState(0))

(array([0.        , 0.24993822, 0.22593797, 0.        , 0.        ,
        0.2275677 , 0.        , 0.        , 0.29655611, 0.        ]),
 array([ 0.        ,  0.95008842, -0.15135721,  0.        ,  0.        ,
         1.86755799,  0.        ,  0.        , -0.97727788,  0.        ]))

In [9]:
from collections import deque
a = deque(maxlen = 5)

for i in range(11):
    a.append(i)
    print(list(a))



[0]
[0, 1]
[0, 1, 2]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]
[6, 7, 8, 9, 10]


In [3]:
%reload_ext autoreload
%autoreload
import ..samplers as s
s = s.BasicSampler(5,["a","b"])

SyntaxError: invalid syntax (<ipython-input-3-310552754404>, line 3)

In [5]:
import numpy as np
help(np.zeros)

Help on built-in function zeros in module numpy.core.multiarray:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    ones_like : Return an array of ones with shape and type of input.
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting v

In [10]:
a = [(1,2),(3,4),(5,6)]
print(a)
aa = list(zip(*a))
print(aa)
bb = [list(x) for x in aa]
print(bb)


[(1, 2), (3, 4), (5, 6)]
[(1, 3, 5), (2, 4, 6)]
[[1, 3, 5], [2, 4, 6]]


In [18]:
import numpy as np
vec = np.array([0.02648392, 0.13453])
def show_numpy_vector_nicely(vec, separator = " ",):
    return separator.join([">{:6.3f}<".format(x) for x in vec])

print(show_numpy_vector_nicely(vec))

> 0.026< > 0.135<


In [23]:
f = lambda x: abs(x)**2
f(np.array([-0.02648392, -0.13453, -2]))


array([7.01398019e-04, 1.80983209e-02, 4.00000000e+00])